version: "3"
containers:
- name: shell
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
  memory: 2048
  resources:
    memory: 2048
virtualbrowsers:
- name: aws
  url: https://signin.aws.amazon.com/console
- name: azure
  url: https://azure.microsoft.com/en-us/get-started/azure-portal
- name: infoblox
  url: https://portal.infoblox.com/
- name: gcp
  url: https://console.cloud.google.com
- name: lab
  url: https://infoblox-igor.s3.eu-west-1.amazonaws.com/Infoblox+Cloud+Speed+DDI.png
- name: aws-discovery
  url: https://github.com/iracic82/AWS_Discovery
- name: flask-ui
  url: http://${_SANDBOX_ID}-websrv1infoblox.iracictechguru.com:5050
gcp_projects:
- name: infoblox-demo
  services:
  - compute.googleapis.com
  - cloudresourcemanager.googleapis.com
  - iam.googleapis.com
  - serviceusage.googleapis.com
aws_accounts:
- name: infoblox-demo
  services:
  - ec2
  - s3
  - apigateway
  - amplifyuibuilder
  - cloudformation
  - autoscaling
  - cloudfront
  - dynamodb
  - iam
  - lambda
  - rds
  - ssm
  - route53
  - route53resolver
  - sns
  - ebs
  - drs
  - cloudwatch
  - events
  - firehose
  - internetmonitor
  - logs
  - networkmonitor
  - oam
  - sqs
  - sts
  regions:
  - eu-west-2
  - eu-central-1
  - eu-central-2
  - eu-north-1
  - eu-south-1
  - eu-south-2
  - eu-west-1
  - eu-west-3
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  managed_policies:
  - arn:aws:iam::aws:policy/AdministratorAccess
azure_subscriptions:
- name: infoblox-tenant
  roles:
  - Owner
secrets:
- name: TF_VAR_windows_admin_password
- name: INFOBLOX_PASSWORD
- name: INFOBLOX_EMAIL
- name: DEMO_HOSTED_ZONE_ID
- name: DEMO_AWS_SECRET_ACCESS_KEY
- name: DEMO_AWS_ACCESS_KEY_ID
- name: Infoblox_Token
