#!/bin/bash
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the setup script"

set-workdir /root/infoblox-lab


# Run Python scripts
cd /root/infoblox-lab/secure-ai-infoblox/scripts
sleep 480
python3 deploy_aws_discovery.py

exit 0